# Generated by Django 3.2.9 on 2022-03-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('url', models.CharField(max_length=2000, verbose_name='URL')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='Hits')),
            ],
            options={
                'verbose_name': 'Page Visit Count',
                'verbose_name_plural': 'Page Visit Counts',
                'ordering': ('-created', '-modified'),
                'get_latest_by': 'created',
            },
        ),
    ]
