# Generated by Django 3.2.9 on 2022-03-13 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220313_0452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageAnalyticsCount',
        ),
    ]
