# Generated by Django 3.2.9 on 2022-03-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_delete_pageanalyticscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAnalyticsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('url', models.CharField(max_length=2000, verbose_name='URL')),
                ('process_time', models.IntegerField(verbose_name='Process Time in sec')),
                ('lang', models.CharField(max_length=100, verbose_name='Language')),
                ('method', models.CharField(max_length=100, verbose_name='Method')),
                ('user_agent', models.CharField(max_length=220, verbose_name='User Data')),
                ('user_ip', models.CharField(max_length=100, verbose_name='User IP')),
            ],
            options={
                'verbose_name': 'Page Visit Count',
                'verbose_name_plural': 'Page Visit Counts',
                'ordering': ('-created',),
                'get_latest_by': 'created',
            },
        ),
    ]
