# Generated by Django 3.2.9 on 2022-03-13 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pageanalyticscount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageanalyticscount',
            options={'get_latest_by': 'created', 'ordering': ('-created',), 'verbose_name': 'Page Analytic Count', 'verbose_name_plural': 'Page Analytic Counts'},
        ),
    ]
