# Generated by Django 3.2.9 on 2022-03-13 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pageanalyticscount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageanalyticscount',
            options={'get_latest_by': 'visit_time', 'ordering': ('-visit_time',), 'verbose_name': 'Page Analytic Count', 'verbose_name_plural': 'Page Analytic Counts'},
        ),
        migrations.RemoveField(
            model_name='pageanalyticscount',
            name='created',
        ),
        migrations.AddField(
            model_name='pageanalyticscount',
            name='visit_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Visit Time'),
            preserve_default=False,
        ),
    ]
